### ISSUE TITLE
运行修改绑定模型的配置例子时报错

### ISSUE THREAD

**Issue by whyseu** [FederatedAI/KubeFATE#112]
报错信息如下：
(venv) [root@0c1e90c8bb50 fate_flow]# python fate_flow_client.py -f bind -c examples/bin                                              d_model_service.json
{
    "retcode": 100,
    "retmsg": "<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILA                                              BLE\n\tdetails = \"Connect Failed\"\n\tdebug_error_string = \"{\"created\":\"@1585048168                                              .113685948\",\"description\":\"Failed to create subchannel\",\"file\":\"src/core/ext/fil                                              ters/client_channel/client_channel.cc\",\"file_line\":2721,\"referenced_errors\":[{\"cre                                              ated\":\"@1585048168.113675586\",\"description\":\"Pick Cancelled\",\"file\":\"src/core/                                              ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":241,\"refe                                              renced_errors\":[{\"created\":\"@1585048168.113456935\",\"description\":\"Connect Failed                                              \",\"file\":\"src/core/ext/filters/client_channel/subchannel.cc\",\"file_line\":689,\"gr                                              pc_status\":14,\"referenced_errors\":[{\"created\":\"@1585048168.113402662\",\"descripti                                              on\":\"Failed to connect to remote host: OS Error\",\"errno\":113,\"file\":\"src/core/li                                              b/iomgr/tcp_client_posix.cc\",\"file_line\":210,\"os_error\":\"No route to host\",\"sysc                                              all\":\"getsockopt(SO_ERROR)\",\"target_address\":\"ipv4:10.0.2.16:8000\"}]}]}]}\"\n>"
}

**Comment by jiahaoc1993** [comment]
确定fate serving正常启动了吗？

**Comment by jiahaoc1993** [comment]
把你的配置文件都贴一下吧

**Comment by whyseu** [comment]
执行前几个示例都是success，到bind报错了。

**Comment by whyseu** [comment]
需要提供哪几个配置文件？是示例中修改的那几个文件？

**Comment by jiahaoc1993** [comment]
是的， 最好把FATE Serving的日志也贴一下

**Comment by dzysunshine** [comment]
我也是这个问题，请问你解决了吗？

**Comment by badawa** [comment]
同问啊，卡好久了不明白原因

**Comment by badawa** [comment]
> 
> 
> 是的， 最好把FATE Serving的日志也贴一下
我出现一样的问题，然后在fate_flow下执行过sh service.sh restart和sh service.sh start都不行，它说服务已经启动，还是会报错，我的日志如下。其中第三个容器的日志只截取了一部分，其余部份是已复制部分的拷贝所以就不复制了。
ID=ed19cc465a47
/*********************serving-9999_serving-proxy_1*******************************/
[root@bogon confs-9999]# docker logs ed19cc465a47

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

Apr 23, 2020 7:51:20 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8059"]
Apr 23, 2020 7:51:20 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Apr 23, 2020 7:51:20 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/9.0.27]
Apr 23, 2020 7:51:20 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring embedded WebApplicationContext
Apr 23, 2020 7:51:22 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8059"]
[root@bogon confs-9999]# 



ID=49fc4f3c9483
/*********************serving-9999_redis_1*******************************/
[root@bogon confs-9999]# docker logs 49fc4f3c9483
1:C 23 Apr 2020 19:51:14.307 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 Apr 2020 19:51:14.307 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 23 Apr 2020 19:51:14.307 # Configuration loaded
1:M 23 Apr 2020 19:51:14.309 * Running mode=standalone, port=6379.
1:M 23 Apr 2020 19:51:14.309 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 23 Apr 2020 19:51:14.309 # Server initialized
1:M 23 Apr 2020 19:51:14.309 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 23 Apr 2020 19:51:14.310 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 23 Apr 2020 19:51:14.310 * Ready to accept connections
[root@bogon confs-9999]# 


ID=66d33c73de29 
/*********************serving-9999_serving-server_1*******************************/
docker logs 66d33c73de29 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

4/23/20 7:52:19 PM =============================================================

-- Counters --------------------------------------------------------------------
requestCount
             count = 0

-- Meters ----------------------------------------------------------------------
request
             count = 0
         mean rate = 0.00 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second

**Comment by badawa** [comment]
> 
> 
> 10.0.2.16这台机器关闭防火墙。"No route to host" 一般是防火墙引起。

多谢，已成功解决。
但是有一点需要注意就是关闭防火墙后docker需要重启，然后各种容器又需要重新开启，所以建议开启容器前就关闭防火墙，再执行service docker restart重启docker。后面绑定模型就可以成功了。

**Comment by dzysunshine** [comment]
> 10.0.2.16这台机器关闭防火墙。"No route to host" 一般是防火墙引起。

非常感谢，一语惊醒梦中人，关闭防火墙后已成功解决。

**Comment by LaynePeng** [comment]
Close issue since it solved.
