### ISSUE TITLE
The version number of docker build is dead and it is not convenient to expand

### ISSUE THREAD

**Issue by xinfang52013141** [FederatedAI/KubeFATE#42]
https://github.com/FederatedAI/FATE/blob/master/docker-build/build_cluster_docker.sh
The version number is dead and it is not convenient to expand.

**Comment by LaynePeng** [comment]
Hi, @xinfang52013141 because there is differences between versions of FATE. For instance, we cannot use v1.0 configuration for FATE v1.1, currently one KubeFATE only fit for one verified version of FATE. That is say, we cannot use KubeFATE v1.0 to deploy FATE v1.1. We catch up the release of FATE and verify it version by version. 
Therefore, we use the fixed hardcoding of version to restrict enduser mismatch the versions to lead problems on perpose. 

If you are talking about contributing convenience, we need to figure out a better way for it. Maybe we can talk in sync meeting between VMware and Webank.
