### ISSUE TITLE
运行homo_NN例子出错

### ISSUE THREAD

**Issue by Cp99nice** [FederatedAI/KubeFATE#507]
![ccb014449dc199f240f23df0e288672](https://user-images.githubusercontent.com/52906517/149257006-48ec40d5-ee27-46b4-9a61-2bdda6cc4cbe.png)
KubeFATE v1.6.0 
log error ： No module named 'tensorflow'

**Comment by owlet42** [comment]
Use a mirror that contains NN.
docker-compose: `enabled_nn=true`
k8s: `enabled_nn: true`
You can also install the missing related components yourself.

**Comment by lemonviv** [comment]
Hi, I use KubeFATE1.8.1 and got this "`No module named tensorflow`" error as well. And I follow the FATE deployment using docker compose instructions described here https://github.com/FederatedAI/KubeFATE/blob/master/docker-deploy/README.md. 

Since the config file is generated automatically by the scripts provided in `generate_config.sh`, where should I add the above solution `enabled_nn=true`? Any suggestions would be highly appreciated. Thanks!
