### ISSUE TITLE
kubefate安装FATE集群创建job失败

### ISSUE THREAD

**Issue by yishionyang** [FederatedAI/KubeFATE#677]
**What deployment mode you are use?  **
Kuberentes.

**What KubeFATE and FATE version you are using?  **
v1.8.0，v1.4.4
**MUST** Please state the KubeFATE and FATE version you found the issue
v1.8.0，v1.4.4
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

 - OS: [Centos]
 - Version [7.6]

**Desktop (please complete the following information):**

**To Reproduce**

创建FATE集群时创建job失败

**What happen?**

创建FATE集群时创建job失败，describe job查看提示
'helm install error, looks like "https://federatedai.github.io/KubeFATE" is not                        
                  a valid Chart repository or cannot be reached: Get "https://federatedai.github.io/KubeFATE/index.yaml":
                  dial tcp 185.199.110.153:443: connect: connection timed out' 

**Screenshots**

![image](https://user-images.githubusercontent.com/7832702/176560887-7bb937d9-47fe-4dd1-be6c-4f19d7039b9b.png)

**Additional context**

**Comment by JingChen23** [comment]
This is because you cannot donwload the chart from github. You can use a proxy to access Github.
Or 
You can manually download the helm chart on our release page. Then call "kubefate chart upload -f" to upload the chart to the database of Kubefate. This is an equivalent of downloading this chart from the Internet.
