### ISSUE TITLE
"docker-compose" Vs "docker compose" in Ubuntu (20.04)

### ISSUE THREAD

**Issue by TomsyPaul** [FederatedAI/KubeFATE#904]
**What deployment mode you are use?  **
docker-compose;

**What KubeFATE and FATE version you are using?  **
1.11.2

**MUST** Please state the KubeFATE and FATE version you found the issue
1.11.2

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
- OS: Ubuntu
 - Version 20.04

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser: Firefox
 - Version: 115.0 

**To Reproduce**

docker compose is the default for snapd. But snapd version needs the docker-compose.yml file to be present in the home tree. But KubeFATE assumes /data/projects folder for file storing..

apt uses docker-compose and works with yml file stored anywhere. But the command should be docker-compose. A compose plugin is possible but that does not work (AFAIK) for Ubuntu 20.04, latest updates. I strongly believe that the problem should be present with recent updates of other Ubuntu Versions also.

The workaround I followed was to install docker from the instructions from docker website https://docs.docker.com/engine/install/ubuntu/  (but it involves many steps) which makes compose a plugin.

**Comment by owlet42** [comment]
The default storage path of docker compose deployment can be modified, modify `dir=/data/projects/fate` of parties.config, use `docker compose` command instead of `docker-compose` because docker-compose-plugin (`docker compose`) is the default choice for docker installation, and Compose standalone (`docker-compose`) is no longer recommended by docker, according to <https://docs.docker.com/compose/install/#scenario-three-install-the- compose-standalone>

**Comment by TomsyPaul** [comment]
Okay.. Thank you.
